name: Aiven Keepalive Checks

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 16 * * *' # 每天 UTC 16:00，也就是台灣時間 00:00

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

  mysql-check:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run MySQL Keepalive
        run: |
          python3 mysql_keepalive.py \
            --db "${{ secrets.AIVEN_MYSQL_DB }}" \
            --host "${{ secrets.AIVEN_MYSQL_HOST }}" \
            --port "${{ secrets.AIVEN_MYSQL_PORT }}" \
            --user "${{ secrets.AIVEN_MYSQL_USER }}" \
            --password "${{ secrets.AIVEN_MYSQL_PASSWORD }}"

  postgresql-check:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run PostgreSQL Keepalive
        run: |
          python3 postgresql_keepalive.py \
            --db "${{ secrets.AIVEN_POSTGRESQL_DB }}" \
            --host "${{ secrets.AIVEN_POSTGRESQL_HOST }}" \
            --port "${{ secrets.AIVEN_POSTGRESQL_PORT }}" \
            --user "${{ secrets.AIVEN_POSTGRESQL_USER }}" \
            --password "${{ secrets.AIVEN_POSTGRESQL_PASSWORD }}"

  valkey-check:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Valkey Keepalive
        run: |
          python3 valkey_keepalive.py \
            --host "${{ secrets.AIVEN_VALKEY_HOST }}" \
            --port "${{ secrets.AIVEN_VALKEY_PORT }}" \
            --user "${{ secrets.AIVEN_VALKEY_USER }}" \
            --password "${{ secrets.AIVEN_VALKEY_PASSWORD }}"
